# Generated by Django 2.2.5 on 2019-09-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190909_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='seats_left',
        ),
    ]
