# Generated by Django 2.2.5 on 2019-09-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190909_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seat',
            field=models.IntegerField(blank=True, default=models.IntegerField()),
        ),
    ]
