# Generated by Django 2.2.5 on 2019-09-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20190909_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seat',
            field=models.IntegerField(default=models.IntegerField(), null=True),
        ),
    ]
