# Generated by Django 2.2.5 on 2019-09-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20190909_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='available_seat',
        ),
    ]
